url: "https://0000099.xyz"
production_url: "https://0000099.xyz"   

title: "0000099"
description: "A blog documenting the journey through computer related problems."
author: "0000099"
email: "0000099@duck.com"
twitter: https://bsky.app/profile/0000099.xyz
logo: /assets/logo.png

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
permalink: /:year/:month/:day/:title/
paginate: 10

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

nav:
  - name: about
    url: /
  - name: posts
    url: /posts/
  - name: philosophy
    url: /philosophy/
  - name: projects
    url: /projects/
  - name: contact
    url: /contact/